### ISSUE TITLE
Beny electronics brand

### ISSUE THREAD

**Issue by suhankins** [rockaysavvy/rockaysavvy.github.io#1]
Clearly a parody of Sony. Can be seen in electronics stores.

It's silly to even remember it exists, but there's a page about [brand of cigarettes](https://rockay.fans/culture/Daw-Stone/), so might as well include brand of electronics too.

![2933080_20240705151307_1](https://github.com/rockaysavvy/rockaysavvy.github.io/assets/90870844/c92b52e8-51b6-4d09-ade9-9d8c31cb9526)
![2933080_20240705151333_1](https://github.com/rockaysavvy/rockaysavvy.github.io/assets/90870844/d01ea518-c3e1-43ac-a6d8-389df96ae4cb)

**Comment by rtkzboss** [comment]
Nice catch, thanks. Will be added in the next site update.
